name: "Calculate Next Version"
description: "Calculate the next version based on VSCode extension versioning guidelines"
inputs:
  release-type:
    description: 'Semantic version type to increment: "major", "minor", "patch", "premajor", "preminor", "prepatch"'
    required: true
    default: "prepatch"
  all-tags:
    description: "Comma-separated list of all version tags in the repository (from get-tags action)"
    required: true
  max-tags:
    description: "Maximum number of recent tags to consider (to avoid issues with older non-SemVer tags)"
    required: false
    default: "10"
outputs:
  next-version:
    description: "The calculated next version with v prefix (e.g., v1.5.0)"
  current-release:
    description: "The current release version (even minor)"
  current-prerelease:
    description: "The current prerelease version (odd minor)"
  latest-version:
    description: "The latest version overall (regardless of type)"

runs:
  # Node 24 is the current Active LTS version as of September 2025
  # See: https://nodejs.org/en/about/previous-releases
  # GitHub Actions currently only supports specific version identifiers (node16, node20, node24)
  using: "node24"
  main: "index.js"
