name: Setup
description: "Sets up the workflow"
runs:
  using: "composite"
  steps:
    - uses: crazy-max/ghaction-github-runtime@v3
    - uses: extractions/setup-just@v2
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
