name: Setup
description: "Sets up the workflow"
runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v2
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - if: ${{ runner.os == 'Linux' }}
      uses: t1m0thyj/unlock-keyring@v1
