name: Setup
description: "Sets up the workflow"
runs:
  using: "composite"
  steps:
    - uses: crazy-max/ghaction-github-runtime@v3
    - uses: extractions/setup-just@v2
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: actions/cache@v4
      with:
        path: var-cache-apt
        key: var-cache-apt-${{ hashFiles('./build/ci/Dockerfile') }}
    - uses: reproducible-containers/buildkit-cache-dance@v2.1.4
      with:
        cache-source: var-cache-apt
        cache-target: /var/cache/apt
    - uses: actions/cache@v4
      with:
        path: var-lib-apt
        key: var-lib-apt-${{ hashFiles('./build/ci/Dockerfile') }}
    - uses: reproducible-containers/buildkit-cache-dance@v2.1.4
      with:
        cache-source: var-lib-apt
        cache-target: /var/lib/apt
