install:
    pip install -e .

install-python-tools:
    pip install 'black==23.*' 'flake8==6.*' 'mypy==1.5.*' 'jupyterlab==4.*'

max_line_length := '99'

validate-python:
    black ./connect_jupyterlab --line-length {{ max_line_length }}
    flake8 ./connect_jupyterlab --max-line-length {{ max_line_length }}
    mypy ./connect_jupyterlab

validate-js:
    npm run lint:check

validate: validate-js validate-python
