alias c := clean
alias t := test

_ci := env_var_or_default("CI", "false")

_debug := env_var_or_default("DEBUG", _ci)

_with_debug := if _debug == "true" {
        "set -x pipefail"
    } else {
        ""
    }

# Quick start
default:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    just clean
    just configure
    just package

assert-command-installed command:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    echo "info: checking if {{ command }} is installed..." 1>&2
    if ! command -v {{ command }} &> /dev/null
    then
        echo "error: {{ command }} is not installed..." 1>&2
        echo "error: please install the binary {{ command }} before proceeding..." 1>&2
        exit 1
    fi

# Deletes ephemeral project files (i.e., cleans the project).
clean:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    rm -rf .vscode-test
    rm -rf dist
    rm -rf node_modules
    rm -rf out
    just ./webviews/homeView/clean


# Install dependencies
deps:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    if [ {{ _ci }} = "true" ]; then
        npm ci --no-audit --no-fund | sed 's/^/debug: /'
        npm --prefix ./webviews/homeView ci --no-audit --no-fund | sed 's/^/debug: /'
        npm --prefix ../../packages/connect-api ci --no-audit --no-fund | sed 's/^/debug: /'
        npm --prefix ../../packages/connect-cloud-api ci --no-audit --no-fund | sed 's/^/debug: /'
    else
        npm install --no-audit --no-fund | sed 's/^/debug: /'
        npm --prefix ./webviews/homeView install --no-audit --no-fund | sed 's/^/debug: /'
        npm --prefix ../../packages/connect-api install --no-audit --no-fund | sed 's/^/debug: /'
        npm --prefix ../../packages/connect-cloud-api install --no-audit --no-fund | sed 's/^/debug: /'
    fi
    just ./webviews/homeView/deps


configure:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    just deps

# Installs the packaged extension on your configured editor using the editor's CLI. The editor CLI defaults to 'code'. Modify this value via the EDITOR environment variable.
install editor="code":
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    just assert-command-installed {{ editor }}

    package=$(just package-name)
    package_path=$(just package-path)

    echo "info: installing extension using {{ editor }}..." 1>&2
    {{ editor }} --install-extension "$package_path/$package" 2>&1 | sed 's/^/debug: /'

# Performs static code analysis with ESLint
lint:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    npm run lint

# Packages the extension.
package:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}
    echo "info: getting package output path..." 1>&2
    path="$(just package-path)"
    mkdir -p "$path"
    echo "info: getting output package name..." 1>&2
    package="$path"/$(just package-name)
    echo "info: packaging..." 1>&2
    if [[ $(just ../../pre-release) == true ]]; then
        prerelease_flag="--pre-release"
    else
        prerelease_flag=""
    fi
    npx --yes @vscode/vsce package -o "$package" $prerelease_flag | sed 's/^/debug: /'
    echo "info: writing package to $package..." 1>&2

package-name:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    name="$(jq -r .name package.json)"
    version="$(just ../../version)"
    echo "$name-$version.vsix"

package-path:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    echo $(readlink -f ../../)/dist

# Executes commands via `npm`. Equivalent to `npm run`.
run *args:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    npm run {{ args }}

# Executes npm test and npm run test-unit
test:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    if [ {{ os() }} == "linux" ]; then
        xvfb-run -a npm test
    else
        npm test
    fi

    npm run test-unit


uninstall editor="code":
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    just assert-command-installed {{ editor }}

    echo "info: uninstalling extension using '{{ editor }}'..." 1>&2
    {{ editor }} --uninstall-extension 'posit.publisher' 2>&1 | sed 's/^/debug: /'
