// Copyright (C) 2026 by Posit Software, PBC.

import * as fs from "fs/promises";
import * as path from "path";
import { stringify as stringifyTOML } from "smol-toml";

import { manifestFromConfig } from "../bundler/manifestFromConfig";
import { createBundle } from "../bundler/bundler";
import type { Manifest, BundleProgressCallback } from "../bundler/types";

import { resolveRPackages } from "./dependencies";
import {
  findExtraDependencies,
  recordExtraDependencies,
  cleanupExtraDependencies,
} from "./extraDependencies";
import { scanRPackages } from "../interpreters/rPackages";
import type { RenvLockfile } from "./rPackageDescriptions";

import type { ConfigurationDetails } from "../api/types/configurations";
import type { ServerType } from "../api/types/contentRecords";
import type { PositronRSettings } from "../api/types/positron";

import { fileExistsAt } from "../interpreters/fsUtils";
import { convertKeysToSnakeCase } from "../toml/convertKeys";
import { stripEmpty, isRecord, expandInlineArrays } from "../toml/tomlHelpers";
import type { ErrorCode } from "../utils/errorTypes";

// ---------------------------------------------------------------------------
// Cancellation
// ---------------------------------------------------------------------------

/**
 * Thrown when a deployment is canceled via AbortSignal.
 * Distinguishable from real errors so callers can handle cancellation differently.
 */
export class CanceledError extends Error {
  constructor() {
    super("Deployment canceled");
    this.name = "CanceledError";
  }
}

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type PublishStep =
  | "createManifest"
  | "preflight"
  | "createNewDeployment"
  | "createDeployment"
  | "createBundle"
  | "uploadBundle"
  | "updateContent"
  | "setEnvVars"
  | "deployBundle"
  | "waitForTask"
  | "validateDeployment";

export type PublishEvent = {
  step: PublishStep;
  status: "start" | "success" | "failure" | "log";
  message?: string;
  /** Typed error code for failure events. */
  errCode?: ErrorCode;
  /** Additional data for event stream injection (e.g., URLs, status codes). */
  data?: Record<string, string>;
};

export type PublishResult = {
  contentId: string;
  dashboardUrl: string;
  directUrl: string;
  logsUrl: string;
  bundleId: string;
};

// ---------------------------------------------------------------------------
// Deployment record types
// ---------------------------------------------------------------------------

export const DEPLOYMENT_SCHEMA_URL =
  "https://cdn.posit.co/publisher/schemas/posit-publishing-record-schema-v3.json";

export const AUTOGEN_HEADER =
  "# This file is automatically generated by Posit Publisher; do not edit.\n";

export type PublishRecord = {
  schema: string;
  serverType: ServerType | string;
  serverUrl: string;
  clientVersion: string;
  createdAt: string;
  type: string;
  configName: string;
  config?: ConfigurationDetails;
  id?: string;
  dashboardUrl?: string;
  directUrl?: string;
  logsUrl?: string;
  bundleId?: string;
  bundleUrl?: string;
  files?: string[];
  requirements?: string[];
  renv?: Record<string, unknown>;
  deployedAt?: string;
  dismissedAt?: string;
  deploymentError?: { code: string; message: string; operation: string };
  connectCloud?: { accountName: string };
};

export function setRecordContentInfo(
  record: PublishRecord,
  contentId: string,
  dashboardUrl: string,
  directUrl: string,
  logsUrl: string,
): void {
  record.id = contentId;
  record.dashboardUrl = dashboardUrl;
  record.directUrl = directUrl;
  record.logsUrl = logsUrl;
}

/**
 * Build a TOML-ready object from the publish record.
 *
 * Top-level keys use snake_case to match the deployment record schema.
 * The renv section uses lowercase keys (r, packages, version, etc.)
 * as defined by the schema, not the PascalCase from renv.lock files.
 */
export function recordToTomlObject(
  record: PublishRecord,
): Record<string, unknown> {
  // Build the configuration section separately — it needs key conversion
  // and empty-value stripping that the other fields don't.
  let configuration: unknown;
  if (record.config) {
    // Clone and remove non-TOML fields, matching Go's toml:"-" tags
    // and the behavior of configWriter/deploymentWriter.
    const cfg = { ...record.config };
    delete cfg.comments;
    delete cfg.alternatives;
    delete cfg.entrypointObjectRef;

    const snakeConfig = convertKeysToSnakeCase(cfg);
    if (isRecord(snakeConfig)) {
      stripEmpty(snakeConfig);
    }
    configuration = snakeConfig;
  }

  // Keys are mapped explicitly because some don't follow simple
  // camelCase→snake_case (e.g. configName → configuration_name,
  // schema → $schema). Undefined values are dropped by smol-toml's
  // stringify, so `|| undefined` omits unset optional fields.
  return {
    $schema: record.schema,
    server_type: record.serverType,
    server_url: record.serverUrl,
    client_version: record.clientVersion,
    created_at: record.createdAt,
    type: record.type,
    configuration_name: record.configName,
    configuration,
    id: record.id || undefined,
    dashboard_url: record.dashboardUrl || undefined,
    direct_url: record.directUrl || undefined,
    logs_url: record.logsUrl || undefined,
    connect_cloud: record.connectCloud
      ? { account_name: record.connectCloud.accountName }
      : undefined,
    deployed_at: record.deployedAt || undefined,
    bundle_id: record.bundleId || undefined,
    bundle_url: record.bundleUrl || undefined,
    files: record.files || undefined,
    requirements: record.requirements || undefined,
    renv: record.renv || undefined,
    dismissed_at: record.dismissedAt || undefined,
    deployment_error: record.deploymentError || undefined,
  };
}

export async function writePublishRecord(
  deploymentPath: string,
  record: PublishRecord,
): Promise<void> {
  // Mirrors Go's WriteDeploymentRecord which sets DeployedAt = now on every
  // write (initial, post-upload, error). This ensures failed/in-progress
  // records reflect when the attempt happened.
  record.deployedAt = new Date().toISOString();
  const obj = recordToTomlObject(record);
  const content =
    AUTOGEN_HEADER + expandInlineArrays(stringifyTOML(obj)) + "\n";
  await fs.mkdir(path.dirname(deploymentPath), { recursive: true });
  await fs.writeFile(deploymentPath, content, "utf-8");
}

// ---------------------------------------------------------------------------
// Manifest building (R scan-if-missing logic)
// ---------------------------------------------------------------------------

export type ManifestResult = {
  manifest: Manifest;
  /** Absolute path to the lockfile used for R packages, if any. */
  lockfilePath: string | undefined;
  /** Parsed lockfile content (PascalCase, as read from renv.lock). */
  lockfile: RenvLockfile | undefined;
};

export async function buildManifest(
  projectDir: string,
  config: ConfigurationDetails,
  rPath: string | undefined,
  positronR: PositronRSettings | undefined,
  onProgress: (event: PublishEvent) => void,
): Promise<ManifestResult> {
  const manifest = manifestFromConfig(config);
  let lockfilePath: string | undefined;
  let lockfile: RenvLockfile | undefined;

  if (config.r) {
    const packageFile = config.r.packageFile || "renv.lock";
    const lockfileOnDisk = path.join(projectDir, packageFile);
    const lockExists = await fileExistsAt(lockfileOnDisk);

    if (lockExists) {
      // Use the existing lockfile directly
      // TS always uses the lockfile mapper (renv.lock), never the library mapper
      onProgress({
        step: "createManifest",
        status: "log",
        message: `Loading packages from renv.lock`,
      });
      const resolved = await resolveRPackages(projectDir, config.r);
      if (resolved) {
        manifest.packages = resolved.packages;
        lockfilePath = resolved.lockfilePath;
        lockfile = resolved.lockfile;
      }
    } else {
      // No lockfile — scan project for R dependencies
      // Mirrors Go's manifest.go:46 log message
      onProgress({
        step: "createManifest",
        status: "log",
        message: "No renv.lock found; automatically scanning for dependencies",
      });

      if (!rPath) {
        throw new Error(
          "R interpreter is required to scan for R package dependencies, " +
            "but none was found. Install R or provide an renv.lock file.",
        );
      }

      // Mirrors Go's r_package_descriptions.go:105
      onProgress({
        step: "createManifest",
        status: "log",
        message: "Detect dependencies from project",
      });

      // Inject implicit deps (e.g. shiny, rmarkdown) so renv can discover them
      const extraDeps = await findExtraDependencies(
        config.type,
        config.hasParameters,
        projectDir,
      );
      const depsFile = await recordExtraDependencies(projectDir, extraDeps);

      try {
        await scanRPackages(projectDir, rPath, packageFile, positronR);
      } finally {
        if (depsFile) {
          await cleanupExtraDependencies(depsFile);
        }
      }

      // Now resolve from the generated lockfile
      onProgress({
        step: "createManifest",
        status: "log",
        message: `Loading packages from renv.lock`,
      });
      const resolved = await resolveRPackages(projectDir, config.r);
      if (resolved) {
        manifest.packages = resolved.packages;
        lockfilePath = resolved.lockfilePath;
        lockfile = resolved.lockfile;
      }
    }

    onProgress({
      step: "createManifest",
      status: "log",
      message: "Done collecting R package descriptions",
    });
  }

  return { manifest, lockfilePath, lockfile };
}

// ---------------------------------------------------------------------------
// Bundle creation with lockfile staging
// ---------------------------------------------------------------------------

export async function buildBundleArchive(
  projectDir: string,
  config: ConfigurationDetails,
  manifest: Manifest,
  lockfilePath: string | undefined,
  onBundleProgress?: BundleProgressCallback,
  syntheticFiles?: Map<string, Buffer>,
): Promise<{ bundle: Buffer; manifest: Manifest }> {
  const basePatterns = config.files?.length ? [...config.files] : ["*"];
  const extraPatterns: string[] = [];
  let stagedLockfile: string | undefined;

  // If the lockfile is not at the project root as renv.lock, stage a copy
  // under .posit/publish/deployments/ and adjust patterns so the bundle
  // includes the staged copy instead of any root renv.lock.
  if (lockfilePath) {
    const rootLockfile = path.join(projectDir, "renv.lock");
    if (path.resolve(lockfilePath) !== path.resolve(rootLockfile)) {
      stagedLockfile = await copyLockfileToPositDir(projectDir, lockfilePath);
      extraPatterns.push("!renv.lock", ".posit/publish/deployments/renv.lock");
    }
  }

  const filePatterns = [...basePatterns, ...extraPatterns];

  try {
    const result = await createBundle({
      projectPath: projectDir,
      manifest,
      filePatterns,
      onProgress: onBundleProgress,
      syntheticFiles,
    });

    return { bundle: result.bundle, manifest: result.manifest };
  } finally {
    if (stagedLockfile) {
      await fs.unlink(stagedLockfile).catch(() => {});
    }
  }
}

export async function copyLockfileToPositDir(
  projectDir: string,
  lockfilePath: string,
): Promise<string> {
  const targetDir = path.join(projectDir, ".posit", "publish", "deployments");
  await fs.mkdir(targetDir, { recursive: true });
  const target = path.join(targetDir, "renv.lock");
  await fs.copyFile(lockfilePath, target);
  return target;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function mergeEnvVars(
  configEnv: Record<string, string> | undefined,
  secrets: Record<string, string> | undefined,
): Record<string, string> | undefined {
  if (!configEnv && !secrets) {
    return undefined;
  }
  const merged: Record<string, string> = {};
  if (configEnv) {
    Object.assign(merged, configEnv);
  }
  if (secrets) {
    Object.assign(merged, secrets);
  }
  return Object.keys(merged).length > 0 ? merged : undefined;
}

/**
 * Convert a PascalCase renv.lock structure to the lowercase shape
 * expected by the deployment record schema.
 *
 * renv.lock uses PascalCase (R, Packages, Version, etc.) but the
 * deployment record schema expects lowercase (r, packages, version).
 * Go handles this via struct tags; we convert explicitly.
 */
export function lockfileToDeploymentRenv(
  lockfile: RenvLockfile,
): Record<string, unknown> {
  const renv: Record<string, unknown> = {};

  if (lockfile.R) {
    renv.r = {
      version: lockfile.R.Version,
      ...(lockfile.R.Repositories && {
        repositories: lockfile.R.Repositories.map((repo) => ({
          name: repo.Name,
          url: repo.URL,
        })),
      }),
    };
  }

  if (lockfile.Packages) {
    const packages: Record<string, Record<string, unknown>> = {};
    for (const [name, pkg] of Object.entries(lockfile.Packages)) {
      const converted: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(pkg)) {
        if (value !== undefined && value !== null && value !== "") {
          converted[pascalToSnake(key)] = value;
        }
      }
      packages[name] = converted;
    }
    renv.packages = packages;
  }

  return renv;
}

/**
 * Convert a PascalCase or camelCase key to snake_case.
 * Handles sequences of capitals: "RemotePkgRef" → "remote_pkg_ref",
 * "URL" → "url", "Package" → "package".
 */
export function pascalToSnake(key: string): string {
  return key
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toLowerCase();
}
