# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.2.dev6+g8f76cd1.d20230503'
__version_tuple__ = version_tuple = (0, 0, 2, 'dev6', 'g8f76cd1.d20230503')
