// Copyright (C) 2026 by Posit Software, PBC.

import * as fs from "fs/promises";
import * as path from "path";
import { stringify as stringifyTOML } from "smol-toml";

import {
  ContentRecord,
  ContentRecordLocation,
  ContentRecordState,
  PreContentRecord,
  ServerType,
} from "../api/types/contentRecords";
import { getConfigPath } from "./configDiscovery";
import { convertKeysToSnakeCase } from "./convertKeys";
import { getDeploymentPath } from "./deploymentDiscovery";
import { loadDeploymentFromFile } from "./deploymentLoader";
import { stripEmpty, isRecord, relativeProjectDir } from "./tomlHelpers";
import { getDashboardUrl, getDirectUrl, getLogsUrl } from "./urlHelpers";

const DEPLOYMENT_SCHEMA_URL =
  "https://cdn.posit.co/publisher/schemas/posit-publishing-record-schema-v3.json";

const AUTOGEN_HEADER =
  "# This file is automatically generated by Posit Publisher; do not edit.\n";

export type CreateDeploymentOptions = {
  saveName: string;
  projectDir: string;
  rootDir: string;
  serverUrl: string;
  serverType: ServerType;
  configName: string;
  cloudAccountName?: string;
  contentId?: string;
  clientVersion: string;
};

/**
 * Create a new deployment record TOML file.
 *
 * Matches the behavior of Go's PostDeploymentsHandlerFunc:
 * - Deployment must not already exist (throws if it does)
 * - If configName is provided, the config file must exist
 * - Writes the autogen header + TOML content
 *
 * @returns The created PreContentRecord with location metadata
 */
export async function createDeploymentRecord(
  opts: CreateDeploymentOptions,
): Promise<PreContentRecord> {
  const absDir = path.resolve(opts.rootDir, opts.projectDir);
  const deploymentPath = getDeploymentPath(absDir, opts.saveName);
  const relDir = relativeProjectDir(absDir, opts.rootDir);

  // Deployment must not exist
  try {
    await fs.access(deploymentPath);
    throw Object.assign(
      new Error(`deployment '${opts.saveName}' already exists`),
      { code: "EEXIST" },
    );
  } catch (e) {
    // ENOENT means the file doesn't exist yet, which is what we want
    if (e instanceof Error && "code" in e && e.code !== "ENOENT") {
      throw e;
    }
  }

  // If configName provided, config must exist
  if (opts.configName) {
    try {
      await fs.access(getConfigPath(absDir, opts.configName));
    } catch {
      throw new Error(`configuration ${opts.configName} not found`);
    }
  }

  // Build deployment record matching Go's deployment.New() + handler logic
  const record: Record<string, unknown> = {
    $schema: DEPLOYMENT_SCHEMA_URL,
    serverType: opts.serverType,
    serverUrl: opts.serverUrl,
    createdAt: new Date().toISOString(),
    type: "unknown",
    configurationName: opts.configName,
    clientVersion: opts.clientVersion,
  };

  if (opts.cloudAccountName || opts.serverType === ServerType.CONNECT_CLOUD) {
    record.connectCloud = {
      accountName: opts.cloudAccountName ?? "",
    };
  }

  if (opts.contentId) {
    record.id = opts.contentId;
    record.dashboardUrl = getDashboardUrl(opts.serverUrl, opts.contentId);
    record.directUrl = getDirectUrl(opts.serverUrl, opts.contentId);
    record.logsUrl = getLogsUrl(opts.serverUrl, opts.contentId);
  }

  // Convert to snake_case, strip empty values, and write
  const snakeObj = convertKeysToSnakeCase(record);
  if (!isRecord(snakeObj)) {
    throw new Error("unexpected: snake_case conversion did not return object");
  }
  stripEmpty(snakeObj);

  const content = AUTOGEN_HEADER + stringifyTOML(snakeObj) + "\n";

  await fs.mkdir(path.dirname(deploymentPath), { recursive: true });
  await fs.writeFile(deploymentPath, content, "utf-8");

  const location: ContentRecordLocation = {
    deploymentName: opts.saveName,
    deploymentPath,
    projectDir: relDir,
  };

  return {
    ...record,
    ...location,
    state: ContentRecordState.NEW,
  } as PreContentRecord;
}

export type PatchDeploymentOptions = {
  configName?: string;
  id?: string;
};

/**
 * Patch an existing deployment record TOML file.
 *
 * Matches the behavior of Go's PatchDeploymentHandlerFunc:
 * - Deployment must exist
 * - If configName is provided, the config file must exist
 * - If id is provided, recomputes dashboard/direct/logs URLs
 * - Writes back the full record with autogen header
 *
 * @returns The updated record (PreContentRecord or ContentRecord)
 */
export async function patchDeploymentRecord(
  deploymentName: string,
  projectDir: string,
  rootDir: string,
  patch: PatchDeploymentOptions,
): Promise<PreContentRecord | ContentRecord> {
  const absDir = path.resolve(rootDir, projectDir);
  const deploymentPath = getDeploymentPath(absDir, deploymentName);
  const relDir = relativeProjectDir(absDir, rootDir);

  // Load existing deployment — will throw ENOENT if missing
  const existing = await loadDeploymentFromFile(deploymentPath, relDir);

  // Apply patches
  if (patch.configName !== undefined && patch.configName !== "") {
    // Config must exist
    try {
      await fs.access(getConfigPath(absDir, patch.configName));
    } catch {
      throw new Error(`configuration ${patch.configName} not found`);
    }
    existing.configurationName = patch.configName;
  }

  if (patch.id !== undefined && patch.id !== "") {
    existing.id = patch.id;
    existing.dashboardUrl = getDashboardUrl(existing.serverUrl, patch.id);
    existing.directUrl = getDirectUrl(existing.serverUrl, patch.id);
    existing.logsUrl = getLogsUrl(existing.serverUrl, patch.id);
  }

  // Prepare for TOML serialization: remove computed/location fields
  const toWrite: Record<string, unknown> = { ...existing };
  delete toWrite.state;
  delete toWrite.deploymentName;
  delete toWrite.deploymentPath;
  delete toWrite.projectDir;

  // Remove the nested configuration location fields that came from the
  // Configuration intersection type on ContentRecord
  delete toWrite.configurationName;
  delete toWrite.configurationPath;

  // Re-add configurationName as a plain field (not from Configuration type)
  toWrite.configurationName = existing.configurationName;

  const snakeObj = convertKeysToSnakeCase(toWrite);
  if (!isRecord(snakeObj)) {
    throw new Error("unexpected: snake_case conversion did not return object");
  }
  stripEmpty(snakeObj);

  const content = AUTOGEN_HEADER + stringifyTOML(snakeObj) + "\n";
  await fs.writeFile(deploymentPath, content, "utf-8");

  // Re-load to return the canonical representation
  return loadDeploymentFromFile(deploymentPath, relDir);
}
