// Copyright (C) 2026 by Posit Software, PBC.

import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  createDeploymentRecord,
  patchDeploymentRecord,
} from "./deploymentWriter";
import { ContentRecordState, ServerType } from "../api/types/contentRecords";

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "deployment-writer-test-"));
  fs.mkdirSync(path.join(tmpDir, ".posit", "publish", "deployments"), {
    recursive: true,
  });
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

const SCHEMA_URL =
  "https://cdn.posit.co/publisher/schemas/posit-publishing-record-schema-v3.json";
const TEST_VERSION = "1.0.0-test";

function writeConfig(name: string): void {
  const configPath = path.join(tmpDir, ".posit", "publish", `${name}.toml`);
  fs.writeFileSync(
    configPath,
    `"$schema" = "https://cdn.posit.co/publisher/schemas/posit-publishing-schema-v3.json"\ntype = "html"\nentrypoint = "index.html"\n`,
  );
}

function writeDeployment(name: string, content: string): string {
  const deploymentPath = path.join(
    tmpDir,
    ".posit",
    "publish",
    "deployments",
    `${name}.toml`,
  );
  fs.writeFileSync(deploymentPath, content, "utf-8");
  return deploymentPath;
}

describe("createDeploymentRecord", () => {
  it("creates a new deployment record", async () => {
    writeConfig("myconfig");

    const record = await createDeploymentRecord({
      saveName: "myapp",
      projectDir: ".",
      rootDir: tmpDir,
      serverUrl: "https://connect.example.com",
      serverType: ServerType.CONNECT,
      configName: "myconfig",
      clientVersion: TEST_VERSION,
    });

    expect(record.state).toBe(ContentRecordState.NEW);
    expect(record.serverUrl).toBe("https://connect.example.com");
    expect(record.serverType).toBe("connect");
    expect(record.configurationName).toBe("myconfig");
    expect(record.deploymentName).toBe("myapp");
    expect(record.createdAt).toBeDefined();

    // Verify file was written
    const filePath = path.join(
      tmpDir,
      ".posit",
      "publish",
      "deployments",
      "myapp.toml",
    );
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain("# This file is automatically generated");
    expect(content).toContain(`"$schema" = "${SCHEMA_URL}"`);
    expect(content).toContain('server_url = "https://connect.example.com"');
    expect(content).toContain('server_type = "connect"');
    expect(content).toContain('configuration_name = "myconfig"');
    expect(content).toContain('type = "unknown"');
  });

  it("creates a Connect Cloud deployment with cloud account", async () => {
    writeConfig("cloud");

    const record = await createDeploymentRecord({
      saveName: "cloud-deploy",
      projectDir: ".",
      rootDir: tmpDir,
      serverUrl: "https://connect.posit.cloud",
      serverType: ServerType.CONNECT_CLOUD,
      configName: "cloud",
      cloudAccountName: "my-account",
      clientVersion: TEST_VERSION,
    });

    expect(record.serverType).toBe("connect_cloud");
    expect(record.connectCloud).toEqual({ accountName: "my-account" });

    const filePath = path.join(
      tmpDir,
      ".posit",
      "publish",
      "deployments",
      "cloud-deploy.toml",
    );
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain("[connect_cloud]");
    expect(content).toContain('account_name = "my-account"');
  });

  it("creates deployment with content ID and computed URLs", async () => {
    writeConfig("myconfig");

    const record = await createDeploymentRecord({
      saveName: "with-id",
      projectDir: ".",
      rootDir: tmpDir,
      serverUrl: "https://connect.example.com",
      serverType: ServerType.CONNECT,
      configName: "myconfig",
      contentId: "abc-123",
      clientVersion: TEST_VERSION,
    });

    expect(record.id).toBe("abc-123");
    expect(record.dashboardUrl).toBe(
      "https://connect.example.com/connect/#/apps/abc-123",
    );
    expect(record.directUrl).toBe(
      "https://connect.example.com/content/abc-123/",
    );
    expect(record.logsUrl).toBe(
      "https://connect.example.com/connect/#/apps/abc-123/logs",
    );
  });

  it("throws if deployment already exists", async () => {
    writeConfig("myconfig");
    writeDeployment(
      "existing",
      `"$schema" = "${SCHEMA_URL}"\nserver_url = "https://example.com"\n`,
    );

    await expect(
      createDeploymentRecord({
        saveName: "existing",
        projectDir: ".",
        rootDir: tmpDir,
        serverUrl: "https://connect.example.com",
        serverType: ServerType.CONNECT,
        configName: "myconfig",
        clientVersion: TEST_VERSION,
      }),
    ).rejects.toThrow(/already exists/);
  });

  it("throws if config does not exist", async () => {
    await expect(
      createDeploymentRecord({
        saveName: "no-config",
        projectDir: ".",
        rootDir: tmpDir,
        serverUrl: "https://connect.example.com",
        serverType: ServerType.CONNECT,
        configName: "nonexistent",
        clientVersion: TEST_VERSION,
      }),
    ).rejects.toThrow(/configuration nonexistent not found/);
  });

  it("allows empty configName", async () => {
    const record = await createDeploymentRecord({
      saveName: "no-config",
      projectDir: ".",
      rootDir: tmpDir,
      serverUrl: "https://connect.example.com",
      serverType: ServerType.CONNECT,
      configName: "",
      clientVersion: TEST_VERSION,
    });

    expect(record.state).toBe(ContentRecordState.NEW);
  });

  it("writes client_version to the TOML file", async () => {
    await createDeploymentRecord({
      saveName: "versioned",
      projectDir: ".",
      rootDir: tmpDir,
      serverUrl: "https://connect.example.com",
      serverType: ServerType.CONNECT,
      configName: "",
      clientVersion: "1.2.3",
    });

    const filePath = path.join(
      tmpDir,
      ".posit",
      "publish",
      "deployments",
      "versioned.toml",
    );
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain('client_version = "1.2.3"');
  });
});

describe("patchDeploymentRecord", () => {
  it("updates configurationName", async () => {
    writeConfig("new-config");
    writeDeployment(
      "patch-test",
      `"$schema" = "${SCHEMA_URL}"\nserver_url = "https://connect.example.com"\nserver_type = "connect"\ncreated_at = "2024-01-19T09:33:33-05:00"\ntype = "html"\nconfiguration_name = "old-config"\n`,
    );

    const record = await patchDeploymentRecord("patch-test", ".", tmpDir, {
      configName: "new-config",
    });

    expect(record.configurationName).toBe("new-config");
  });

  it("updates id and recomputes URLs", async () => {
    writeDeployment(
      "patch-id",
      `"$schema" = "${SCHEMA_URL}"\nserver_url = "https://connect.example.com"\nserver_type = "connect"\ncreated_at = "2024-01-19T09:33:33-05:00"\ntype = "html"\n`,
    );

    const record = await patchDeploymentRecord("patch-id", ".", tmpDir, {
      id: "new-guid-456",
    });

    expect(record.id).toBe("new-guid-456");
    expect(record.dashboardUrl).toBe(
      "https://connect.example.com/connect/#/apps/new-guid-456",
    );
    expect(record.directUrl).toBe(
      "https://connect.example.com/content/new-guid-456/",
    );
    expect(record.logsUrl).toBe(
      "https://connect.example.com/connect/#/apps/new-guid-456/logs",
    );
  });

  it("throws if deployment does not exist", async () => {
    await expect(
      patchDeploymentRecord("nonexistent", ".", tmpDir, {
        configName: "foo",
      }),
    ).rejects.toThrow(/ENOENT/);
  });

  it("throws if config does not exist", async () => {
    writeDeployment(
      "patch-bad-config",
      `"$schema" = "${SCHEMA_URL}"\nserver_url = "https://connect.example.com"\nserver_type = "connect"\ncreated_at = "2024-01-19T09:33:33-05:00"\ntype = "html"\n`,
    );

    await expect(
      patchDeploymentRecord("patch-bad-config", ".", tmpDir, {
        configName: "nonexistent",
      }),
    ).rejects.toThrow(/configuration nonexistent not found/);
  });
});
