package deployment

// Copyright (C) 2023 by Posit Software, PBC.

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
	"github.com/rstudio/connect-client/internal/accounts"
	"github.com/rstudio/connect-client/internal/config"
	"github.com/rstudio/connect-client/internal/project"
	"github.com/rstudio/connect-client/internal/schema"
	"github.com/rstudio/connect-client/internal/types"
	"github.com/rstudio/connect-client/internal/util"
)

type Deployment struct {
	// Predeployment and full deployment fields
	Schema        string              `toml:"$schema" json:"$schema"`
	ServerType    accounts.ServerType `toml:"server-type" json:"serverType"`
	ServerURL     string              `toml:"server-url" json:"serverUrl"`
	ClientVersion string              `toml:"client-version" json:"-"`
	CreatedAt     string              `toml:"created-at" json:"createdAt"`
	ConfigName    string              `toml:"configuration-name" json:"configurationName"`

	// Full deployment fields
	ID            types.ContentID   `toml:"id,omitempty" json:"id"`
	DeployedAt    string            `toml:"deployed-at,omitempty" json:"deployedAt"`
	BundleID      types.BundleID    `toml:"bundle-id,omitempty" json:"bundleId"`
	BundleURL     string            `toml:"bundle-url,omitempty" json:"bundleUrl"`
	DashboardURL  string            `toml:"dashboard-url,omitempty" json:"dashboardUrl"`
	DirectURL     string            `toml:"direct-url,omitempty" json:"directUrl"`
	Error         *types.AgentError `toml:"deployment-error,omitempty" json:"deploymentError"`
	Files         []string          `toml:"files,multiline,omitempty" json:"files"`
	Configuration *config.Config    `toml:"configuration,omitempty" json:"configuration"`
}

func New() *Deployment {
	return &Deployment{
		Schema:        schema.DeploymentSchemaURL,
		ServerType:    accounts.ServerTypeConnect,
		ClientVersion: project.Version,
		CreatedAt:     time.Now().Format(time.RFC3339),
		Configuration: nil,
		Files:         nil,
	}
}

func GetDeploymentsPath(base util.AbsolutePath) util.AbsolutePath {
	return base.Join(".posit", "publish", "deployments")
}

func GetDeploymentPath(base util.AbsolutePath, name string) util.AbsolutePath {
	return GetDeploymentsPath(base).Join(name + ".toml")
}

func ListDeploymentFiles(base util.AbsolutePath) ([]util.AbsolutePath, error) {
	dir := GetDeploymentsPath(base)
	return dir.Glob("*.toml")
}

func UntitledDeploymentName(base util.AbsolutePath) (string, error) {
	for i := 1; ; i++ {
		name := fmt.Sprintf("Untitled-%d", i)
		exists, err := GetDeploymentPath(base, name).Exists()
		if err != nil {
			return "", err
		}
		if !exists {
			return name, nil
		}
	}
}

func SaveNameFromPath(path util.AbsolutePath) string {
	return strings.TrimSuffix(path.Base(), ".toml")
}

func RenameDeployment(base util.AbsolutePath, oldName, newName string) error {
	err := util.ValidateFilename(newName)
	if err != nil {
		return err
	}
	oldPath := GetDeploymentPath(base, oldName)
	newPath := GetDeploymentPath(base, newName)
	return oldPath.Rename(newPath.Path)
}

func FromFile(path util.AbsolutePath) (*Deployment, error) {
	err := ValidateFile(path)
	if err != nil {
		return nil, err
	}
	d := New()

	err = util.ReadTOMLFile(path, d)
	if err != nil {
		return nil, err
	}
	return d, nil
}

func ValidateFile(path util.AbsolutePath) error {
	validator, err := schema.NewValidator[Deployment](schema.DeploymentSchemaURL)
	if err != nil {
		return err
	}
	return validator.ValidateTOMLFile(path)
}

const autogenHeader = "# This file is automatically generated by Posit Publisher; do not edit.\n"

func (d *Deployment) Write(w io.Writer) error {
	_, err := w.Write([]byte(autogenHeader))
	if err != nil {
		return err
	}
	enc := toml.NewEncoder(w)
	return enc.Encode(d)
}

func (d *Deployment) WriteFile(path util.AbsolutePath) error {
	err := path.Dir().MkdirAll(0777)
	if err != nil {
		return err
	}
	f, err := path.Create()
	if err != nil {
		return err
	}
	defer f.Close()
	err = d.Write(f)
	if err != nil {
		return err
	}
	return nil
}
