// Copyright (C) 2026 by Posit Software, PBC.

// Cross-language golden tests: verify that the TypeScript connectContentFromConfig
// produces the same ConnectContent as Go's ConnectContentFromConfig for identical inputs.
//
// The golden JSON files in testdata/content/ are generated by the Go test:
//   UPDATE_GOLDEN=1 go test -run TestGenerateContentGoldenFiles ./internal/clients/connect/

import { readFileSync } from "fs";
import { join } from "path";
import { describe, expect, it } from "vitest";
import { connectContentFromConfig } from "./connectContentFromConfig";
import { ConfigurationDetails, ContentType } from "../api/types/configurations";
import { ProductType } from "../api/types/contentRecords";

const testdataDir = join(__dirname, "testdata", "content");

function loadGolden(name: string): Record<string, unknown> {
  const raw = readFileSync(join(testdataDir, `${name}.json`), "utf-8");
  return JSON.parse(raw);
}

function buildAndParse(cfg: ConfigurationDetails): Record<string, unknown> {
  const content = connectContentFromConfig(cfg);
  const json = JSON.stringify(content);
  return JSON.parse(json);
}

function cfg(overrides: Partial<ConfigurationDetails>): ConfigurationDetails {
  return {
    $schema: "" as ConfigurationDetails["$schema"],
    productType: ProductType.CONNECT,
    type: ContentType.UNKNOWN,
    validate: true,
    ...overrides,
  };
}

describe("golden file tests (Go parity)", () => {
  it("minimal", () => {
    const actual = buildAndParse(cfg({}));
    expect(actual).toEqual(loadGolden("minimal"));
  });

  it("title-description", () => {
    const actual = buildAndParse(
      cfg({ title: "My Dashboard", description: "Shows important metrics" }),
    );
    expect(actual).toEqual(loadGolden("title-description"));
  });

  it("runtime-full", () => {
    const actual = buildAndParse(
      cfg({
        title: "Runtime App",
        connect: {
          runtime: {
            connectionTimeout: 10,
            readTimeout: 20,
            initTimeout: 30,
            idleTimeout: 40,
            maxProcesses: 5,
            minProcesses: 1,
            maxConnsPerProcess: 50,
            loadFactor: 0.75,
          },
        },
      }),
    );
    expect(actual).toEqual(loadGolden("runtime-full"));
  });

  it("access-full", () => {
    const actual = buildAndParse(
      cfg({
        connect: {
          access: {
            runAs: "rstudio-connect",
            runAsCurrentUser: true,
          },
        },
      }),
    );
    expect(actual).toEqual(loadGolden("access-full"));
  });

  it("kubernetes-full", () => {
    const actual = buildAndParse(
      cfg({
        connect: {
          kubernetes: {
            memoryRequest: 1024,
            memoryLimit: 2048,
            cpuRequest: 0.5,
            cpuLimit: 2.0,
            amdGpuLimit: 1,
            nvidiaGpuLimit: 2,
            serviceAccountName: "my-sa",
            defaultImageName: "my-image:latest",
            defaultREnvironmentManagement: true,
            defaultPyEnvironmentManagement: false,
          },
        },
      }),
    );
    expect(actual).toEqual(loadGolden("kubernetes-full"));
  });

  it("all-sections", () => {
    const actual = buildAndParse(
      cfg({
        title: "Full App",
        description: "Everything configured",
        connect: {
          runtime: {
            connectionTimeout: 15,
            initTimeout: 60,
            maxProcesses: 3,
          },
          access: {
            runAs: "publisher",
            runAsCurrentUser: false,
          },
          kubernetes: {
            memoryRequest: 512,
            cpuLimit: 1.0,
          },
        },
      }),
    );
    expect(actual).toEqual(loadGolden("all-sections"));
  });
});
