// Copyright (C) 2026 by Posit Software, PBC.

// Cross-language golden tests: verify that the TypeScript manifestFromConfig
// produces the same manifest as Go's NewManifestFromConfig for identical inputs.
//
// The golden JSON files in testdata/ are generated by the Go test:
//   UPDATE_GOLDEN=1 go test -run TestGenerateGoldenFiles ./internal/bundles/

import { readFileSync } from "fs";
import { join } from "path";
import { describe, expect, it } from "vitest";
import { manifestFromConfig } from "./manifestFromConfig";
import { manifestToJSON } from "./manifest";
import { ConfigurationDetails, ContentType } from "../api/types/configurations";
import { ProductType } from "../api/types/contentRecords";

const testdataDir = join(__dirname, "testdata");

function loadGolden(name: string): Record<string, unknown> {
  const raw = readFileSync(join(testdataDir, `${name}.json`), "utf-8");
  return JSON.parse(raw);
}

function buildAndParse(cfg: ConfigurationDetails): Record<string, unknown> {
  const manifest = manifestFromConfig(cfg);
  const json = manifestToJSON(manifest).toString("utf-8");
  return JSON.parse(json);
}

function cfg(overrides: Partial<ConfigurationDetails>): ConfigurationDetails {
  return {
    $schema: "" as ConfigurationDetails["$schema"],
    productType: ProductType.CONNECT,
    type: ContentType.UNKNOWN,
    validate: true,
    ...overrides,
  };
}

describe("golden file tests (Go parity)", () => {
  it("python-dash-full", () => {
    const actual = buildAndParse(
      cfg({
        type: ContentType.PYTHON_DASH,
        entrypoint: "app:myapp",
        hasParameters: true,
        python: {
          version: "3.4.5",
          packageFile: "requirements.in",
          packageManager: "pip",
        },
        r: {
          version: "4.5.6",
          packageFile: "renv.lock",
          packageManager: "renv",
        },
        quarto: {
          version: "1.2.3",
          engines: ["jupyter"],
        },
      }),
    );
    expect(actual).toEqual(loadGolden("python-dash-full"));
  });

  it("jupyter-notebook", () => {
    const actual = buildAndParse(
      cfg({
        type: ContentType.JUPYTER_NOTEBOOK,
        entrypoint: "notebook.ipynb",
        hasParameters: true,
        python: {
          version: "3.4.5",
          packageFile: "requirements.in",
          packageManager: "pip",
        },
        jupyter: {
          hideAllInput: true,
        },
      }),
    );
    expect(actual).toEqual(loadGolden("jupyter-notebook"));
  });

  it("version-requirements", () => {
    const actual = buildAndParse(
      cfg({
        type: ContentType.QUARTO_STATIC,
        entrypoint: "report.qmd",
        python: {
          version: "3.4.5",
          packageFile: "requirements.in",
          packageManager: "pip",
          requiresPython: ">=3.4.5",
        },
        r: {
          version: "4.5.6",
          packageFile: "renv.lock",
          packageManager: "renv",
          requiresR: ">=4.5.6",
        },
      }),
    );
    expect(actual).toEqual(loadGolden("version-requirements"));
  });

  it("integration-requests", () => {
    const actual = buildAndParse(
      cfg({
        type: ContentType.PYTHON_FASTAPI,
        entrypoint: "app:app",
        integrationRequests: [
          {
            guid: "123456789abcdef",
            name: "my-integration",
            description: "Vertex AI OAuth integration",
            authType: "Viewer",
            type: "vertex-ai",
            config: { auth_mode: "Confidential" },
          },
        ],
      }),
    );
    expect(actual).toEqual(loadGolden("integration-requests"));
  });

  it("python-uv", () => {
    const actual = buildAndParse(
      cfg({
        type: ContentType.PYTHON_FASTAPI,
        entrypoint: "app:app",
        python: {
          version: "3.11",
          packageFile: "requirements.txt",
          packageManager: "uv",
        },
      }),
    );
    expect(actual).toEqual(loadGolden("python-uv"));
  });

  it("python-auto", () => {
    const actual = buildAndParse(
      cfg({
        type: ContentType.PYTHON_FASTAPI,
        entrypoint: "app:app",
        python: {
          version: "3.11",
          packageFile: "requirements.txt",
          packageManager: "auto",
        },
      }),
    );
    expect(actual).toEqual(loadGolden("python-auto"));
  });

  it("python-none", () => {
    const actual = buildAndParse(
      cfg({
        type: ContentType.PYTHON_FASTAPI,
        entrypoint: "app:app",
        python: {
          version: "3.11",
          packageFile: "requirements.txt",
          packageManager: "none",
        },
      }),
    );
    expect(actual).toEqual(loadGolden("python-none"));
  });

  it("html-static", () => {
    const actual = buildAndParse(
      cfg({
        type: ContentType.HTML,
        entrypoint: "index.html",
      }),
    );
    expect(actual).toEqual(loadGolden("html-static"));
  });

  it("rmd-shiny", () => {
    const actual = buildAndParse(
      cfg({
        type: ContentType.RMD_SHINY,
        entrypoint: "report.Rmd",
        r: {
          version: "4.3.1",
          packageFile: "renv.lock",
          packageManager: "renv",
        },
      }),
    );
    expect(actual).toEqual(loadGolden("rmd-shiny"));
  });
});
