default: install lint test build

install *args:
    pnpm install {{ args }}

lint *args:
    pnpm run lint {{ args }}

build *args:
    quasar build {{ args }}

test-all: build
    quasar test --unit vitest
    quasar test --e2e cypress
    # go test -race ./...

# Will
test:
    npx vitest

dev:
    just install
    quasar dev

clean:
    quasar clean
