// Copyright (C) 2026 by Posit Software, PBC.

import * as path from "path";
import * as fs from "fs/promises";
import {
  ContentType,
  PythonConfig,
  RConfig,
} from "src/api/types/configurations";
import { detectPythonInterpreter } from "src/interpreters/pythonInterpreter";
import { detectRInterpreter } from "src/interpreters/rInterpreter";
import { hasRpy2Dependency } from "./helpers/rpy2Checker";
import { PartialConfig } from "./types";

const initialComment = ` Configuration file generated by Posit Publisher.
 Please review and modify as needed. See the documentation for more options:
 https://github.com/posit-dev/publisher/blob/main/docs/configuration.md`;

// Content types that require a `[python]` section per the schema.
const PYTHON_CONTENT_TYPES: ContentType[] = [
  ContentType.JUPYTER_NOTEBOOK,
  ContentType.JUPYTER_VOILA,
  ContentType.PYTHON_BOKEH,
  ContentType.PYTHON_DASH,
  ContentType.PYTHON_FASTAPI,
  ContentType.PYTHON_FLASK,
  ContentType.PYTHON_GRADIO,
  ContentType.PYTHON_PANEL,
  ContentType.PYTHON_SHINY,
  ContentType.PYTHON_STREAMLIT,
];

// Content types that require an `[r]` section per the schema.
const R_CONTENT_TYPES: ContentType[] = [
  ContentType.R_PLUMBER,
  ContentType.R_SHINY,
  ContentType.RMD_SHINY,
  ContentType.RMD,
];

// Content types that require a `[quarto]` section per the schema.
const QUARTO_CONTENT_TYPES: ContentType[] = [
  ContentType.QUARTO,
  ContentType.QUARTO_SHINY,
  ContentType.QUARTO_STATIC,
];

export function isPythonContentType(type: ContentType): boolean {
  return PYTHON_CONTENT_TYPES.includes(type);
}

export function isRRequiredContentType(type: ContentType): boolean {
  return R_CONTENT_TYPES.includes(type);
}

export function isQuartoContentType(type: ContentType): boolean {
  return QUARTO_CONTENT_TYPES.includes(type);
}

export interface NormalizedConfig {
  type: ContentType;
  entrypoint: string;
  entrypointObjectRef?: string;
  title: string;
  source?: string;
  hasParameters?: boolean;
  files: string[];
  python?: PythonConfig;
  r?: RConfig;
  quarto?: { version: string; engines?: string[] };
  comments: string[];
  alternatives?: PartialConfig[];
}

/**
 * Normalize a partial config by filling in interpreter info, file lists, and title.
 */
export async function normalizeConfig(
  cfg: PartialConfig,
  baseDir: string,
  pythonPath?: string,
  rPath?: string,
  entrypoint?: string,
): Promise<NormalizedConfig> {
  // Fall back entrypoint
  let resolvedEntrypoint = cfg.entrypoint;
  if (!resolvedEntrypoint) {
    resolvedEntrypoint = entrypoint || "unknown";
  }

  // Default title is the name of the project directory
  const title = cfg.title || path.basename(baseDir);

  // Default files list
  const files =
    cfg.files && cfg.files.length > 0
      ? [...cfg.files]
      : [`/${resolvedEntrypoint}`];

  // Python inspection
  // Only use inspection to find the package file for the files list. Leave
  // the python config as an empty placeholder so that version/packageManager/etc.
  // are determined at publish time via defaults, not baked into the configuration file.
  let pythonConfig: PythonConfig | undefined;
  if (cfg.python) {
    pythonConfig = { version: "", packageFile: "", packageManager: "" };
    const result = await detectPythonInterpreter(baseDir, pythonPath);
    if (result.config.packageFile) {
      files.push(`/${result.config.packageFile}`);
    }
  }

  // R inspection
  let rConfig: RConfig | undefined;

  // Check if R is explicitly needed (detector set cfg.r)
  let needR = cfg.r !== undefined;

  // Additional R checks
  if (
    !needR &&
    cfg.type !== ContentType.HTML &&
    cfg.type !== ContentType.NODEJS &&
    !isPythonContentType(cfg.type)
  ) {
    // For non-HTML, non-Python content: check for renv.lock
    const renvPath = path.join(baseDir, "renv.lock");
    try {
      await fs.access(renvPath);
      needR = true;
    } catch {
      // No renv.lock
    }
  }

  if (!needR && isPythonContentType(cfg.type)) {
    // For Python content: check for rpy2 dependency
    const hasRpy2 = await hasRpy2Dependency(baseDir);
    if (hasRpy2) {
      needR = true;
    }
  }

  // Only use inspection to find the package file for the files list. Leave
  // the R config as an empty placeholder so that version/packageManager/etc.
  // are determined at publish time via defaults.
  if (needR) {
    rConfig = { version: "", packageFile: "", packageManager: "" };
    const result = await detectRInterpreter(baseDir, rPath);
    if (result.config.packageFile) {
      files.push(`/${result.config.packageFile}`);
    }
  }

  // Node.js: bundle package.json and package-lock.json. There is no [node]
  // section to populate — Connect picks the runtime from package.json's
  // engines.node at build time.
  if (cfg.type === ContentType.NODEJS) {
    files.push("/package.json", "/package-lock.json");
  }

  const comments = initialComment.split("\n");

  return {
    type: cfg.type,
    entrypoint: resolvedEntrypoint,
    entrypointObjectRef: cfg.entrypointObjectRef,
    title,
    source: cfg.source,
    hasParameters: cfg.hasParameters,
    files,
    python: pythonConfig,
    r: rConfig,
    quarto: cfg.quarto,
    comments,
    // Pass alternatives through without normalization. The detector already
    // sets the fields the UI needs (type, entrypoint, source, title, files).
    // Alternatives are never written to TOML.
    alternatives: cfg.alternatives,
  };
}
