// Copyright (C) 2026 by Posit Software, PBC.

import * as path from "path";
import * as fs from "fs/promises";
import {
  ContentType,
  PythonConfig,
  RConfig,
} from "src/api/types/configurations";
import { detectPythonInterpreter } from "src/interpreters/pythonInterpreter";
import { detectRInterpreter } from "src/interpreters/rInterpreter";
import { hasRpy2Dependency } from "./helpers/rpy2Checker";
import { PartialConfig } from "./types";

const initialComment = ` Configuration file generated by Posit Publisher.
 Please review and modify as needed. See the documentation for more options:
 https://github.com/posit-dev/publisher/blob/main/docs/configuration.md`;

function isPythonContentType(type: ContentType): boolean {
  const pythonTypes: ContentType[] = [
    ContentType.JUPYTER_NOTEBOOK,
    ContentType.JUPYTER_VOILA,
    ContentType.PYTHON_BOKEH,
    ContentType.PYTHON_DASH,
    ContentType.PYTHON_FASTAPI,
    ContentType.PYTHON_FLASK,
    ContentType.PYTHON_GRADIO,
    ContentType.PYTHON_PANEL,
    ContentType.PYTHON_SHINY,
    ContentType.PYTHON_STREAMLIT,
  ];
  return pythonTypes.includes(type);
}

export interface NormalizedConfig {
  type: ContentType;
  entrypoint: string;
  entrypointObjectRef?: string;
  title: string;
  source?: string;
  hasParameters?: boolean;
  files: string[];
  python?: PythonConfig;
  r?: RConfig;
  quarto?: { version: string; engines?: string[] };
  comments: string[];
  alternatives?: NormalizedConfig[];
}

/**
 * Normalize a partial config by filling in interpreter info, file lists, and title.
 * Mirrors Go's initialize/initialize.go normalizeConfig().
 */
export async function normalizeConfig(
  cfg: PartialConfig,
  baseDir: string,
  pythonPath?: string,
  rPath?: string,
  entrypoint?: string,
): Promise<NormalizedConfig> {
  // Fall back entrypoint
  let resolvedEntrypoint = cfg.entrypoint;
  if (!resolvedEntrypoint) {
    resolvedEntrypoint = entrypoint || "unknown";
  }

  // Default title is the name of the project directory
  const title = cfg.title || path.basename(baseDir);

  // Default files list
  const files =
    cfg.files && cfg.files.length > 0
      ? [...cfg.files]
      : [`/${resolvedEntrypoint}`];

  // Python inspection
  // Match Go behavior: only use inspection to find the package file for the
  // files list. Leave the python config as an empty placeholder so that
  // version/packageManager/etc. are determined at publish time via defaults,
  // not baked into the configuration file.
  let pythonConfig: PythonConfig | undefined;
  if (cfg.python) {
    pythonConfig = { version: "", packageFile: "", packageManager: "" };
    const result = await detectPythonInterpreter(baseDir, pythonPath);
    if (result.config.packageFile) {
      files.push(`/${result.config.packageFile}`);
    }
  }

  // R inspection
  let rConfig: RConfig | undefined;

  // Check if R is explicitly needed (detector set cfg.r)
  let needR = cfg.r !== undefined;

  // Additional R checks (matching Go logic)
  if (
    !needR &&
    cfg.type !== ContentType.HTML &&
    !isPythonContentType(cfg.type)
  ) {
    // For non-HTML, non-Python content: check for renv.lock
    const renvPath = path.join(baseDir, "renv.lock");
    try {
      await fs.access(renvPath);
      needR = true;
    } catch {
      // No renv.lock
    }
  }

  if (!needR && isPythonContentType(cfg.type)) {
    // For Python content: check for rpy2 dependency
    const hasRpy2 = await hasRpy2Dependency(baseDir);
    if (hasRpy2) {
      needR = true;
    }
  }

  // Match Go behavior: only use inspection to find the package file for the
  // files list. Leave the R config as an empty placeholder so that
  // version/packageManager/etc. are determined at publish time via defaults.
  if (needR) {
    rConfig = { version: "", packageFile: "", packageManager: "" };
    const result = await detectRInterpreter(baseDir, rPath);
    // Only add package file if it exists
    if (result.config.packageFile) {
      const lockPath = path.join(baseDir, result.config.packageFile);
      try {
        await fs.access(lockPath);
        files.push(`/${result.config.packageFile}`);
      } catch {
        // Lockfile doesn't exist, don't add
      }
    }
  }

  const comments = initialComment.split("\n");

  return {
    type: cfg.type,
    entrypoint: resolvedEntrypoint,
    entrypointObjectRef: cfg.entrypointObjectRef,
    title,
    source: cfg.source,
    hasParameters: cfg.hasParameters,
    files,
    python: pythonConfig,
    r: rConfig,
    quarto: cfg.quarto,
    comments,
  };
}
