package pydeps

// Copyright (C) 2026 by Posit Software, PBC.

import (
	"testing"

	"github.com/posit-dev/publisher/internal/util"
	"github.com/posit-dev/publisher/internal/util/utiltest"
	"github.com/spf13/afero"
	"github.com/stretchr/testify/suite"
)

type GenerateSuite struct {
	utiltest.Suite
	cwd util.AbsolutePath
	fs  afero.Fs
}

func TestGenerateSuite(t *testing.T) {
	suite.Run(t, new(GenerateSuite))
}

func (s *GenerateSuite) SetupTest() {
	s.fs = afero.NewMemMapFs()
	cwd, err := util.Getwd(s.fs)
	s.NoError(err)
	s.cwd = cwd
	err = cwd.MkdirAll(0700)
	s.NoError(err)
}

func (s *GenerateSuite) TestGenerateRequirements_NoSourceFiles() {
	reqs, ok := GenerateRequirements(s.cwd, nil)
	s.False(ok)
	s.Nil(reqs)
}

func (s *GenerateSuite) TestGenerateRequirements_PrefersPyLock() {
	// Create pylock.toml, uv.lock, and pyproject.toml
	pylockPath := s.cwd.Join("pylock.toml")
	err := pylockPath.WriteFile([]byte(`lock-version = "1.0"
created-by = "uv"

[[packages]]
name = "flask"
version = "3.0.1"
`), 0666)
	s.NoError(err)

	uvPath := s.cwd.Join("uv.lock")
	err = uvPath.WriteFile([]byte(`version = 1

[[package]]
name = "flask"
version = "3.0.2"
source = { registry = "https://pypi.org/simple" }
`), 0666)
	s.NoError(err)

	pyPath := s.cwd.Join("pyproject.toml")
	err = pyPath.WriteFile([]byte(`[project]
name = "myproject"
dependencies = ["flask>=3.0"]
`), 0666)
	s.NoError(err)

	reqs, ok := GenerateRequirements(s.cwd, nil)
	s.True(ok)
	// Should use pylock.toml (PEP 751), not uv.lock or pyproject.toml
	s.Equal([]string{"flask==3.0.1"}, reqs)
}

func (s *GenerateSuite) TestGenerateRequirements_PrefersUvLockOverPyProject() {
	// Create uv.lock and pyproject.toml (no pylock.toml)
	uvPath := s.cwd.Join("uv.lock")
	err := uvPath.WriteFile([]byte(`version = 1

[[package]]
name = "flask"
version = "3.0.2"
source = { registry = "https://pypi.org/simple" }
`), 0666)
	s.NoError(err)

	pyPath := s.cwd.Join("pyproject.toml")
	err = pyPath.WriteFile([]byte(`[project]
name = "myproject"
dependencies = ["flask>=3.0"]
`), 0666)
	s.NoError(err)

	reqs, ok := GenerateRequirements(s.cwd, nil)
	s.True(ok)
	// Should use uv.lock (pinned), not pyproject.toml
	s.Equal([]string{"flask==3.0.2"}, reqs)
}

func (s *GenerateSuite) TestGenerateRequirements_FallsToPyProject() {
	pyPath := s.cwd.Join("pyproject.toml")
	err := pyPath.WriteFile([]byte(`[project]
name = "myproject"
dependencies = ["requests>=2.20", "numpy"]
`), 0666)
	s.NoError(err)

	reqs, ok := GenerateRequirements(s.cwd, nil)
	s.True(ok)
	s.Equal([]string{"requests>=2.20", "numpy"}, reqs)
}

func (s *GenerateSuite) TestGenerateRequirements_PassesOptionalGroups() {
	pyPath := s.cwd.Join("pyproject.toml")
	err := pyPath.WriteFile([]byte(`[project]
name = "myproject"
dependencies = ["requests"]

[project.optional-dependencies]
dev = ["pytest"]
`), 0666)
	s.NoError(err)

	reqs, ok := GenerateRequirements(s.cwd, []string{"dev"})
	s.True(ok)
	s.Equal([]string{"requests", "pytest"}, reqs)
}

func (s *GenerateSuite) TestCanGenerateRequirements_WithPyLock() {
	pylockPath := s.cwd.Join("pylock.toml")
	err := pylockPath.WriteFile([]byte("lock-version = \"1.0\"\n"), 0666)
	s.NoError(err)

	can, err := CanGenerateRequirements(s.cwd)
	s.NoError(err)
	s.True(can)
}

func (s *GenerateSuite) TestCanGenerateRequirements_WithUvLock() {
	uvPath := s.cwd.Join("uv.lock")
	err := uvPath.WriteFile([]byte("version = 1\n"), 0666)
	s.NoError(err)

	can, err := CanGenerateRequirements(s.cwd)
	s.NoError(err)
	s.True(can)
}

func (s *GenerateSuite) TestCanGenerateRequirements_WithPyProject() {
	pyPath := s.cwd.Join("pyproject.toml")
	err := pyPath.WriteFile([]byte(`[project]
name = "myproject"
dependencies = ["requests"]
`), 0666)
	s.NoError(err)

	can, err := CanGenerateRequirements(s.cwd)
	s.NoError(err)
	s.True(can)
}

func (s *GenerateSuite) TestCanGenerateRequirements_NoSources() {
	can, err := CanGenerateRequirements(s.cwd)
	s.NoError(err)
	s.False(can)
}

func (s *GenerateSuite) TestCanGenerateRequirements_PyProjectWithoutDeps() {
	// pyproject.toml exists but has no [project].dependencies
	pyPath := s.cwd.Join("pyproject.toml")
	err := pyPath.WriteFile([]byte("[tool.ruff]\nline-length = 88\n"), 0666)
	s.NoError(err)

	can, err := CanGenerateRequirements(s.cwd)
	s.NoError(err)
	s.False(can)
}

func (s *GenerateSuite) TestFormatRequirementsContent() {
	reqs := []string{"flask==3.0.2", "requests==2.31.0"}
	content := FormatRequirementsContent(reqs)
	expected := "# requirements.txt auto-generated by Posit Publisher\n# from pylock.toml, uv.lock, or pyproject.toml\nflask==3.0.2\nrequests==2.31.0\n"
	s.Equal(expected, string(content))
}
