package pydeps

// Copyright (C) 2026 by Posit Software, PBC.

import (
	"strings"

	"github.com/posit-dev/publisher/internal/util"
)

// GenerateRequirements attempts to produce a requirements.txt content
// from pylock.toml, uv.lock, or pyproject.toml, in that order of priority.
//
// pylock.toml (PEP 751) and uv.lock are preferred because they contain
// pinned, exact versions for the full transitive dependency set.
// pyproject.toml provides the declared (possibly unpinned) direct
// dependencies.
//
// Returns the requirement lines and true if generation succeeded,
// or nil and false if no suitable source file was found.
func GenerateRequirements(base util.AbsolutePath, optionalGroups []string) ([]string, bool) {
	// Try pylock.toml first (PEP 751 standard lockfile, pinned)
	reqs, err := ReadPyLockDependencies(base)
	if err == nil && reqs != nil {
		return reqs, true
	}

	// Try uv.lock (pinned, full transitive set)
	reqs, err = ReadUvLockDependencies(base)
	if err == nil && reqs != nil {
		return reqs, true
	}

	// Fall back to pyproject.toml (declared, possibly unpinned)
	reqs, err = ReadPyProjectDependencies(base, optionalGroups)
	if err == nil && reqs != nil {
		return reqs, true
	}

	return nil, false
}

// CanGenerateRequirements checks whether a requirements.txt can be
// generated from available dependency source files (pylock.toml, uv.lock,
// or pyproject.toml). This is a lightweight check used by pre-flight validation.
func CanGenerateRequirements(base util.AbsolutePath) (bool, error) {
	hasPyLock, err := HasPyLock(base)
	if err != nil {
		return false, err
	}
	if hasPyLock {
		return true, nil
	}

	hasUv, err := HasUvLock(base)
	if err != nil {
		return false, err
	}
	if hasUv {
		return true, nil
	}

	hasPyProject, err := HasPyProjectDependencies(base)
	if err != nil {
		return false, err
	}
	return hasPyProject, nil
}

// FormatRequirementsContent produces the full text of a requirements.txt
// file from a list of requirement lines, with an auto-generation header.
func FormatRequirementsContent(reqs []string) []byte {
	header := "# requirements.txt auto-generated by Posit Publisher\n" +
		"# from pylock.toml, uv.lock, or pyproject.toml\n"
	content := header + strings.Join(reqs, "\n") + "\n"
	return []byte(content)
}
