// Copyright (C) 2026 by Posit Software, PBC.

import { execFile } from "node:child_process";
import { writeFile, unlink } from "node:fs/promises";
import path from "node:path";
import os from "node:os";

import { ScanPythonPackagesResponse } from "src/api/types/packages";

const PYTHON_SCAN_TIMEOUT = 300_000; // 5 minutes - scanning large projects can be slow

/**
 * Result of scanning Python dependencies in a project.
 */
export interface ScanPythonDependenciesResult {
  /** List of package specifiers (e.g., ["numpy==1.22.3", "pandas"]) */
  requirements: string[];
  /** List of imports that could not be mapped to installed packages */
  incomplete: string[];
  /** Path to the Python interpreter used for scanning */
  python: string;
}

/**
 * Validate the base filename of a requirements.txt path.
 * The saveName may contain slashes (e.g. "subdir/requirements.txt"),
 * but the base filename must not contain path traversal components.
 */
function validateSaveName(saveName: string): void {
  const base = path.posix.basename(saveName);
  if (!base || base === "." || base === "..") {
    throw new Error(
      `Invalid requirements filename: ${JSON.stringify(saveName)}`,
    );
  }
  // Check for directory traversal
  const normalized = path.posix.normalize(saveName);
  if (normalized.startsWith("..") || path.posix.isAbsolute(normalized)) {
    throw new Error(`Invalid requirements path: ${JSON.stringify(saveName)}`);
  }
}

/**
 * Scan Python package dependencies in a project directory.
 *
 * This runs a Python script that:
 * 1. Walks the project directory for .py, .ipynb, .qmd files
 * 2. Extracts imports using ast.parse (.py), JSON parsing (.ipynb), regex (.qmd)
 * 3. Filters stdlib imports using sys.stdlib_module_names (3.10+) with fallback for 3.9
 * 4. Filters local imports (matching local .py files or directories)
 * 5. Maps imports to installed packages via importlib.metadata + top_level.txt
 * 6. Outputs JSON: {"requirements": [...], "incomplete": [...]}
 *
 * If saveName is provided, writes a requirements.txt file with the auto-generated header.
 *
 * @param projectDir Absolute path to the project directory
 * @param pythonPath Path to the Python executable
 * @param saveName Optional relative path for requirements.txt (default: don't write file)
 * @returns Parsed scan result with requirements, incomplete, and python path
 */
export async function scanPythonDependencies(
  projectDir: string,
  pythonPath: string,
  saveName?: string,
): Promise<ScanPythonDependenciesResult> {
  const result = await runPythonScanScript(projectDir, pythonPath);

  if (saveName) {
    validateSaveName(saveName);
    const requirementsPath = path.join(projectDir, saveName);

    // Format: auto-generated header + package specs
    const header = `# requirements.txt auto-generated by Posit Publisher\n# using ${pythonPath}\n`;
    const content = header + result.requirements.join("\n") + "\n";

    await writeFile(requirementsPath, content, "utf-8");
  }

  return {
    requirements: result.requirements,
    incomplete: result.incomplete,
    python: pythonPath,
  };
}

/**
 * Run the Python dependency scan script and parse its JSON output.
 * Exported for testing.
 *
 * @param projectDir Absolute path to the project directory
 * @param pythonPath Path to the Python executable
 * @returns Parsed scan result
 */
export async function runPythonScanScript(
  projectDir: string,
  pythonPath: string,
): Promise<ScanPythonPackagesResponse> {
  // Embedded Python script that scans project files and outputs JSON
  const script = `
import sys
import os
import ast
import json
from pathlib import Path
from typing import Set, Dict, List
import re

# Use chr(96) to avoid literal backticks in JS template literal
FENCE = chr(96) * 3

# Python 3.9 stdlib fallback (sys.stdlib_module_names added in 3.10)
STDLIB_39 = {
    "__future__", "__main__", "_thread", "_tkinter", "abc", "aifc", "argparse", "array", "ast", "asyncio", "atexit", "audioop", "base64", "bdb", "binascii", "bisect", "builtins", "bz2", "calendar", "cgi", "cgitb", "chunk", "cmath", "cmd", "code", "codecs", "codeop", "collections", "colorsys", "compileall", "concurrent", "configparser", "contextlib", "contextvars", "copy", "copyreg", "cProfile", "crypt", "csv", "ctypes", "curses", "dataclasses", "datetime", "dbm", "decimal", "difflib", "dis", "doctest", "email", "encodings", "ensurepip", "enum", "errno", "faulthandler", "fcntl", "filecmp", "fileinput", "fnmatch", "fractions", "ftplib", "functools", "gc", "getopt", "getpass", "gettext", "glob", "graphlib", "grp", "gzip", "hashlib", "heapq", "hmac", "html", "http", "idlelib", "imaplib", "imghdr", "importlib", "inspect", "io", "ipaddress", "itertools", "json", "keyword", "lib2to3", "linecache", "locale", "logging", "lzma", "mailbox", "mailcap", "marshal", "math", "mimetypes", "mmap", "modulefinder", "msilib", "msvcrt", "multiprocessing", "netrc", "nis", "nntplib", "numbers", "operator", "optparse", "os", "ossaudiodev", "pathlib", "pdb", "pickle", "pickletools", "pipes", "pkgutil", "platform", "plistlib", "poplib", "posix", "pprint", "profile", "pstats", "pty", "pwd", "py_compile", "pyclbr", "pydoc", "queue", "quopri", "random", "re", "readline", "reprlib", "resource", "rlcompleter", "runpy", "sched", "secrets", "select", "selectors", "shelve", "shlex", "shutil", "signal", "site", "sitecustomize", "smtplib", "sndhdr", "socket", "socketserver", "spwd", "sqlite3", "ssl", "stat", "statistics", "string", "stringprep", "struct", "subprocess", "sunau", "symtable", "sys", "sysconfig", "syslog", "tabnanny", "tarfile", "telnetlib", "tempfile", "termios", "test", "textwrap", "threading", "time", "timeit", "tkinter", "token", "tokenize", "tomllib", "trace", "traceback", "tracemalloc", "tty", "turtle", "turtledemo", "types", "typing", "unicodedata", "unittest", "urllib", "usercustomize", "uu", "uuid", "venv", "warnings", "wave", "weakref", "webbrowser", "winreg", "winsound", "wsgiref", "xdrlib", "xml", "xmlrpc", "zipapp", "zipfile", "zipimport", "zlib", "zoneinfo"
}

def get_stdlib_modules() -> Set[str]:
    """Get set of stdlib module names (3.10+ or fallback for 3.9)."""
    if sys.version_info >= (3, 10):
        return set(sys.stdlib_module_names)
    return STDLIB_39

def extract_py_imports(file_path: Path) -> Set[str]:
    """Extract top-level import names from a .py file using AST."""
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            tree = ast.parse(f.read(), filename=str(file_path))

        imports = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.add(alias.name.split(".")[0])
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    imports.add(node.module.split(".")[0])
        return imports
    except Exception:
        return set()

def extract_ipynb_imports(file_path: Path) -> Set[str]:
    """Extract imports from .ipynb notebook cells using AST."""
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            nb = json.load(f)

        imports = set()
        for cell in nb.get("cells", []):
            if cell.get("cell_type") == "code":
                source = cell.get("source", [])
                # source is either a list of strings or a single string
                if isinstance(source, list):
                    code = "".join(source)
                else:
                    code = source

                try:
                    tree = ast.parse(code)
                    for node in ast.walk(tree):
                        if isinstance(node, ast.Import):
                            for alias in node.names:
                                imports.add(alias.name.split(".")[0])
                        elif isinstance(node, ast.ImportFrom):
                            if node.module:
                                imports.add(node.module.split(".")[0])
                except Exception:
                    pass
        return imports
    except Exception:
        return set()

def extract_qmd_imports(file_path: Path) -> Set[str]:
    """Extract imports from .qmd Python code blocks using regex + AST."""
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()

        imports = set()
        # Match Python code blocks: \`\`\`{python} ... \`\`\` or \`\`\`python ... \`\`\`
        pattern = re.compile(
            FENCE + r"(?:\\{python\\}|python)\\s*\\n(.*?)\\n" + FENCE,
            re.DOTALL | re.MULTILINE
        )
        for match in pattern.finditer(content):
            code = match.group(1)
            try:
                tree = ast.parse(code)
                for node in ast.walk(tree):
                    if isinstance(node, ast.Import):
                        for alias in node.names:
                            imports.add(alias.name.split(".")[0])
                    elif isinstance(node, ast.ImportFrom):
                        if node.module:
                            imports.add(node.module.split(".")[0])
            except Exception:
                pass
        return imports
    except Exception:
        return set()

def find_local_modules(project_dir: Path) -> Set[str]:
    """Find local Python modules (files/dirs) in project."""
    local = set()
    for item in project_dir.rglob("*.py"):
        # Convert path relative to project_dir into module name
        rel = item.relative_to(project_dir)
        parts = list(rel.parts[:-1]) + [rel.stem]
        if parts and parts[0] != "__pycache__":
            local.add(parts[0])

    # Add directories containing __init__.py
    for item in project_dir.rglob("__init__.py"):
        rel = item.relative_to(project_dir).parent
        if rel != Path(".") and rel.parts[0] != "__pycache__":
            local.add(rel.parts[0])

    return local

def build_package_map() -> Dict[str, str]:
    """Map import names to package names using importlib.metadata."""
    try:
        from importlib.metadata import distributions
    except ImportError:
        return {}

    pkg_map = {}
    for dist in distributions():
        pkg_name = dist.metadata.get("Name", "")
        if not pkg_name:
            continue

        # Read top_level.txt to get import names
        try:
            top_level = dist.read_text("top_level.txt")
            if top_level:
                for line in top_level.strip().split("\\n"):
                    import_name = line.strip()
                    if import_name:
                        pkg_map[import_name] = pkg_name
        except Exception:
            pass

    return pkg_map

def get_package_version(pkg_name: str) -> str:
    """Get installed version of a package."""
    try:
        from importlib.metadata import version
        return version(pkg_name)
    except Exception:
        return ""

def main():
    if len(sys.argv) < 2:
        print(json.dumps({"error": "Usage: script.py <project_dir>"}), file=sys.stderr)
        sys.exit(1)

    project_dir = Path(sys.argv[1])
    if not project_dir.exists():
        print(json.dumps({"error": f"Project directory not found: {project_dir}"}), file=sys.stderr)
        sys.exit(1)

    # Collect all imports from project files
    all_imports = set()
    for ext, extractor in [
        ("*.py", extract_py_imports),
        ("*.ipynb", extract_ipynb_imports),
        ("*.qmd", extract_qmd_imports),
    ]:
        for file_path in project_dir.rglob(ext):
            all_imports.update(extractor(file_path))

    # Filter out stdlib and local imports
    stdlib = get_stdlib_modules()
    local = find_local_modules(project_dir)
    third_party = all_imports - stdlib - local

    # Map imports to packages
    pkg_map = build_package_map()
    requirements = []
    incomplete = []

    for imp in sorted(third_party):
        pkg_name = pkg_map.get(imp)
        if pkg_name:
            version = get_package_version(pkg_name)
            if version:
                requirements.append(f"{pkg_name}=={version}")
            else:
                requirements.append(pkg_name)
        else:
            # Not found in installed packages - assume installable under import name
            incomplete.append(imp)
            requirements.append(imp)

    result = {
        "requirements": requirements,
        "incomplete": incomplete
    }
    print(json.dumps(result))

if __name__ == "__main__":
    main()
`;

  // Write script to a temp file
  const tmpFile = path.join(
    os.tmpdir(),
    `publisher-pydeps-${Date.now()}-${Math.random().toString(36).slice(2)}.py`,
  );
  await writeFile(tmpFile, script, "utf-8");

  try {
    return await runPythonScript(pythonPath, tmpFile, projectDir);
  } finally {
    // Clean up temp file
    try {
      await unlink(tmpFile);
    } catch {
      // Ignore cleanup errors
    }
  }
}

function runPythonScript(
  pythonPath: string,
  scriptFile: string,
  projectDir: string,
): Promise<ScanPythonPackagesResponse> {
  return new Promise((resolve, reject) => {
    execFile(
      pythonPath,
      ["-E", scriptFile, projectDir],
      {
        timeout: PYTHON_SCAN_TIMEOUT,
      },
      (error, stdout, stderr) => {
        if (error) {
          const msg = stderr
            ? `Python scan failed: ${stderr}`
            : `Python scan failed: ${error.message}`;
          reject(new Error(msg));
          return;
        }

        try {
          const result = JSON.parse(stdout.trim());
          if (result.error) {
            reject(new Error(`Python scan failed: ${result.error}`));
            return;
          }
          resolve(result);
        } catch (parseError) {
          reject(
            new Error(
              `Failed to parse Python scan output: ${parseError instanceof Error ? parseError.message : String(parseError)}`,
            ),
          );
        }
      },
    );
  });
}
