// Copyright (C) 2026 by Posit Software, PBC.

import { execFile } from "node:child_process";
import { writeFile, unlink, mkdir } from "node:fs/promises";
import path from "node:path";
import os from "node:os";

const PYTHON_SCAN_TIMEOUT = 60_000; // 1 minute

/**
 * Result of scanning Python dependencies in a project.
 */
export interface ScanPythonDependenciesResult {
  /** List of package specifiers (e.g., ["numpy==1.22.3", "pandas"]) */
  requirements: string[];
  /** List of imports that could not be mapped to installed packages */
  incomplete: string[];
  /** Path to the Python interpreter used for scanning */
  python: string;
}

/**
 * Validate the base filename of a requirements.txt path.
 * The saveName may contain slashes (e.g. "subdir/requirements.txt"),
 * but must not escape the project directory via traversal or absolute paths.
 */
function validateSaveName(saveName: string, projectDir: string): void {
  const base = path.basename(saveName);
  if (!base || base === "." || base === "..") {
    throw new Error(
      `Invalid requirements filename: ${JSON.stringify(saveName)}`,
    );
  }
  if (path.isAbsolute(saveName)) {
    throw new Error(`Invalid requirements path: ${JSON.stringify(saveName)}`);
  }
  // Containment check: resolved path must stay within projectDir
  const resolved = path.resolve(projectDir, saveName);
  const rel = path.relative(path.resolve(projectDir), resolved);
  if (path.isAbsolute(rel) || rel === ".." || rel.startsWith(".." + path.sep)) {
    throw new Error(`Invalid requirements path: ${JSON.stringify(saveName)}`);
  }
}

/**
 * Scan Python package dependencies in a project directory.
 *
 * This runs a Python script that:
 * 1. Walks the project directory for .py, .ipynb, .qmd files
 * 2. Extracts imports using ast.parse (.py), JSON parsing (.ipynb), regex (.qmd)
 * 3. Filters stdlib imports using sys.stdlib_module_names (3.10+) with fallback for 3.9
 * 4. Filters local imports (matching local .py files or directories)
 * 5. Maps imports to installed packages via importlib.metadata + top_level.txt
 * 6. Outputs JSON: {"requirements": [...], "incomplete": [...]}
 *
 * If saveName is provided, writes a requirements.txt file with the auto-generated header.
 *
 * @param projectDir Absolute path to the project directory
 * @param pythonPath Path to the Python executable
 * @param saveName Optional relative path for requirements.txt (default: don't write file)
 * @returns Parsed scan result with requirements, incomplete, and python path
 */
export async function scanPythonDependencies(
  projectDir: string,
  pythonPath: string,
  saveName?: string,
): Promise<ScanPythonDependenciesResult> {
  if (saveName) {
    validateSaveName(saveName, projectDir);
  }

  const result = await runPythonScanScript(projectDir, pythonPath);

  if (saveName) {
    const requirementsPath = path.join(projectDir, saveName);
    await mkdir(path.dirname(requirementsPath), { recursive: true });

    // Format: auto-generated header + package specs
    const header = `# requirements.txt auto-generated by Posit Publisher\n# using ${pythonPath}\n`;
    const content = header + result.requirements.join("\n") + "\n";

    await writeFile(requirementsPath, content, "utf-8");
  }

  return {
    requirements: result.requirements,
    incomplete: result.incomplete,
    python: pythonPath,
  };
}

/**
 * Run the Python dependency scan script and parse its JSON output.
 * Exported for testing.
 *
 * @param projectDir Absolute path to the project directory
 * @param pythonPath Path to the Python executable
 * @returns Parsed scan result
 */
export async function runPythonScanScript(
  projectDir: string,
  pythonPath: string,
): Promise<{ requirements: string[]; incomplete: string[] }> {
  // Embedded Python script that scans project files and outputs JSON.
  // Uses only stdlib modules available in Python 3.9+.
  // IMPORTANT: No literal backticks allowed — use FENCE = chr(96) * 3.
  const script = `
import ast
import json
import os
import sys
from pathlib import Path

FENCE = chr(96) * 3

# --- stdlib detection ---

_STDLIB = getattr(sys, "stdlib_module_names", None)
if _STDLIB is None:
    _STDLIB = {
        "__future__", "__main__", "_thread", "_tkinter", "abc", "aifc",
        "argparse", "array", "ast", "asyncio", "atexit", "audioop",
        "base64", "bdb", "binascii", "bisect", "builtins", "bz2",
        "calendar", "cgi", "cgitb", "chunk", "cmath", "cmd", "code",
        "codecs", "codeop", "collections", "colorsys", "compileall",
        "concurrent", "configparser", "contextlib", "contextvars",
        "copy", "copyreg", "cProfile", "crypt", "csv", "ctypes",
        "curses", "dataclasses", "datetime", "dbm", "decimal",
        "difflib", "dis", "doctest", "email", "encodings", "ensurepip",
        "enum", "errno", "faulthandler", "fcntl", "filecmp",
        "fileinput", "fnmatch", "fractions", "ftplib", "functools",
        "gc", "getopt", "getpass", "gettext", "glob", "graphlib",
        "grp", "gzip", "hashlib", "heapq", "hmac", "html", "http",
        "idlelib", "imaplib", "imghdr", "importlib", "inspect", "io",
        "ipaddress", "itertools", "json", "keyword", "lib2to3",
        "linecache", "locale", "logging", "lzma", "mailbox", "mailcap",
        "marshal", "math", "mimetypes", "mmap", "modulefinder",
        "msilib", "msvcrt", "multiprocessing", "netrc", "nis",
        "nntplib", "numbers", "operator", "optparse", "os",
        "ossaudiodev", "pathlib", "pdb", "pickle", "pickletools",
        "pipes", "pkgutil", "platform", "plistlib", "poplib", "posix",
        "pprint", "profile", "pstats", "pty", "pwd", "py_compile",
        "pyclbr", "pydoc", "queue", "quopri", "random", "re",
        "readline", "reprlib", "resource", "rlcompleter", "runpy",
        "sched", "secrets", "select", "selectors", "shelve", "shlex",
        "shutil", "signal", "site", "sitecustomize", "smtplib",
        "sndhdr", "socket", "socketserver", "spwd", "sqlite3", "ssl",
        "stat", "statistics", "string", "stringprep", "struct",
        "subprocess", "sunau", "symtable", "sys", "sysconfig",
        "syslog", "tabnanny", "tarfile", "telnetlib", "tempfile",
        "termios", "test", "textwrap", "threading", "time", "timeit",
        "tkinter", "token", "tokenize", "tomllib", "trace",
        "traceback", "tracemalloc", "tty", "turtle", "turtledemo",
        "types", "typing", "unicodedata", "unittest", "urllib",
        "usercustomize", "uu", "uuid", "venv", "warnings", "wave",
        "weakref", "webbrowser", "winreg", "winsound", "wsgiref",
        "xdrlib", "xml", "xmlrpc", "zipapp", "zipfile", "zipimport",
        "zlib", "zoneinfo",
    }

SKIP_DIRS = {".git", "__pycache__", "node_modules", ".venv", "venv",
             ".tox", ".eggs", ".mypy_cache", ".pytest_cache"}

# --- import extraction helpers ---

def _imports_from_ast(source):
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    names = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                base = alias.name.split(".")[0]
                if base:
                    names.append(base)
        elif isinstance(node, ast.ImportFrom):
            if node.level == 0 and node.module:
                base = node.module.split(".")[0]
                if base:
                    names.append(base)
    return names


def extract_py(file_path):
    try:
        source = file_path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return []
    return _imports_from_ast(source)


def extract_ipynb(file_path):
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            nb = json.load(f)
    except (json.JSONDecodeError, UnicodeDecodeError, OSError):
        return []
    code_lines = []
    for cell in nb.get("cells", []):
        if not isinstance(cell, dict) or cell.get("cell_type") != "code":
            continue
        source = cell.get("source", [])
        if isinstance(source, list):
            code_lines.extend(source)
        elif isinstance(source, str):
            code_lines.append(source)
    return _imports_from_ast("".join(code_lines))


def extract_qmd(file_path):
    try:
        content = file_path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return []
    lines = content.split("\\n")
    in_block = False
    code_lines = []
    for line in lines:
        if in_block:
            if line.startswith(FENCE):
                in_block = False
                code_lines.append("")
            else:
                code_lines.append(line.rstrip("\\r"))
        elif line.startswith(FENCE + "{python"):
            in_block = True
    return _imports_from_ast("\\n".join(code_lines))


def is_local_import(name, file_dir):
    return (file_dir / name).is_dir() or (file_dir / (name + ".py")).is_file()


# --- package mapping ---

def build_package_map():
    from importlib.metadata import distributions
    mapping = {}
    for dist in distributions():
        pkg_name = dist.metadata["Name"]
        version = dist.metadata["Version"]
        top_level_text = dist.read_text("top_level.txt")
        if top_level_text:
            for import_name in top_level_text.strip().splitlines():
                import_name = import_name.strip()
                if import_name:
                    mapping[import_name] = (pkg_name, version)
        else:
            mapping[pkg_name] = (pkg_name, version)
            normalized = pkg_name.replace("-", "_").lower()
            if normalized != pkg_name:
                mapping[normalized] = (pkg_name, version)
    return mapping


# --- main ---

def scan_project(project_dir):
    base = Path(project_dir)
    all_imports = set()

    for root, dirs, files in os.walk(base):
        root_path = Path(root)
        dirs[:] = [d for d in dirs if not d.startswith(".") and d not in SKIP_DIRS]
        for fname in files:
            file_path = root_path / fname
            ext = fname.rsplit(".", 1)[-1].lower() if "." in fname else ""
            file_imports = []

            if ext == "py":
                file_imports = extract_py(file_path)
            elif ext == "ipynb":
                file_imports = extract_ipynb(file_path)
            elif ext == "qmd":
                file_imports = extract_qmd(file_path)
            else:
                continue

            for name in file_imports:
                if name not in _STDLIB and not is_local_import(name, file_path.parent):
                    all_imports.add(name)

    pkg_map = build_package_map()
    requirements = []
    incomplete = []

    seen_packages = set()
    for import_name in sorted(all_imports):
        if import_name in pkg_map:
            pkg_name, version = pkg_map[import_name]
            if pkg_name not in seen_packages:
                requirements.append(f"{pkg_name}=={version}")
                seen_packages.add(pkg_name)
        else:
            requirements.append(import_name)
            incomplete.append(import_name)

    return {"requirements": requirements, "incomplete": incomplete}


if __name__ == "__main__":
    project_dir = sys.argv[1]
    if not os.path.isdir(project_dir):
        print(f"Project directory not found: {project_dir}", file=sys.stderr)
        sys.exit(1)
    result = scan_project(project_dir)
    json.dump(result, sys.stdout)
`;

  // Write script to a temp file
  const tmpFile = path.join(
    os.tmpdir(),
    `publisher-pydeps-${Date.now()}-${Math.random().toString(36).slice(2)}.py`,
  );
  await writeFile(tmpFile, script, "utf-8");

  try {
    return await runPythonScript(pythonPath, tmpFile, projectDir);
  } finally {
    // Clean up temp file
    try {
      await unlink(tmpFile);
    } catch {
      // Ignore cleanup errors
    }
  }
}

function runPythonScript(
  pythonPath: string,
  scriptFile: string,
  projectDir: string,
): Promise<{ requirements: string[]; incomplete: string[] }> {
  return new Promise((resolve, reject) => {
    execFile(
      pythonPath,
      ["-E", scriptFile, projectDir],
      {
        timeout: PYTHON_SCAN_TIMEOUT,
      },
      (error, stdout, stderr) => {
        if (error) {
          const msg = stderr
            ? `Python scan failed: ${stderr}`
            : `Python scan failed: ${error.message}`;
          reject(new Error(msg));
          return;
        }

        try {
          const result = JSON.parse(stdout.trim());
          if (result.error) {
            reject(new Error(`Python scan failed: ${result.error}`));
            return;
          }
          resolve(result);
        } catch (parseError) {
          reject(
            new Error(
              `Failed to parse Python scan output: ${parseError instanceof Error ? parseError.message : String(parseError)}`,
            ),
          );
        }
      },
    );
  });
}
