FROM cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1

RUN mkdir /app
WORKDIR /app

COPY package*.json ./
RUN npm ci && npm cache clean --force

ENV PATH /app/node_modules/.bin:$PATH

WORKDIR /app/e2e

CMD ["cypress", "run"]
