# Defines an image that installs connect-manager and a Connect DEB
# The Connect host to be used as the publishing target.
# Multiple versions of R, Python and Quarto are installed and configured.

FROM e2ebase AS connect-publisher-e2e

RUN export TZ=America/New_York

# Setup users and groups using cloned script from Connect's docker image: 
# docker/ubuntu24/Dockerfile

# An incoming Jenkins uid/gid alters how the account is created. Allows
# matching uid/gid on the launching Jenkins agent. Configured late to keep
# more layers reusable.
ARG JENKINS_GID=999
ARG JENKINS_UID=999

# Create the jenkins user with the same id:gid as the jenkins-node
RUN groupadd -g $JENKINS_GID jenkins && \
    useradd -m -d /var/lib/jenkins -u $JENKINS_UID -g jenkins jenkins

# give jenkins root(sudo) access
RUN echo "%jenkins  ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/jenkins
RUN chmod 440 /etc/sudoers.d/jenkins

# Create a cache dir owned by jenkins to prevent rosetta race condition on Apple
# Silicon and allow Quarto content to run. Without this, the dir may be owned by
# root.
RUN mkdir -p /var/lib/jenkins/.cache && chown jenkins:jenkins /var/lib/jenkins/.cache

# The data-scientists group is use for testing permissions for shared group resources.
# This group can be used when testing multi-user/alternate-user execution with a non-primary, shared group
RUN groupadd data-scientists

# The rstudio-connect user mirrors the user we create during installation.
# This user is often used as the default RunAs user by tests and when testing
# primary-user execution.
#
# The rstudio-connect user DOES NOT have a home directory. Its primary group
# is rstudio-connect. It is also a member of the shared data-scientists group
RUN useradd -r -M -s /usr/sbin/nologin -G data-scientists \
    -c "System user for rstudio-connect daemon" rstudio-connect

# The shiny-runner user is an alternate RunAs user. This user can be used when
# testing multi-user/alternate-user execution.
#
# The shiny-runner user DOES have a home directory. Its primary group is
# shiny-runner. It is a member of the data-scientists, jenkins, and rstudio-connect groups.
RUN useradd -r -m -s /usr/sbin/nologin -G data-scientists,jenkins,rstudio-connect \
    -c "Alternate RunAs user with home directory" shiny-runner

# The nohome-runner user is an alternate RunAs user. This user can be used
# when testing multi-user/alternate user execution.
#
# The nohome-runner DOES NOT have a home directory. Its primary group is
# nohome-runner. It is a member of the data-scientists, jenkins, and rstudio-connect groups.
RUN useradd -r -M -s /usr/sbin/nologin -G data-scientists,jenkins,rstudio-connect \
    -c "Alternate RunAs user without a home directory" nohome-runner

# Ths nonmember-runner user is an invalid RunAs user. This user can be used
# when testing group validation.
#
# The nonmember-runner user is NOT a member of the jenkins or rstudio-connect
# groups.
RUN useradd -r -m -s /usr/sbin/nologin \
    -c "Alternate RunAs user with home directory" nonmember-runner

# because licensing
RUN mkdir /var/lib/rstudio-connect

# Enable git when running as users other than the GH actions runner
# https://github.com/actions/checkout/issues/766
RUN git config --global --add safe.directory /connect
RUN su - jenkins -c 'git config --global --add safe.directory /connect'

WORKDIR /opt/connect-manager

ARG CONNECT_MANAGER_VERSION=0.5.1
RUN curl -fsSL "https://cdn.rstudio.com/connect/connect-manager/${CONNECT_MANAGER_VERSION}/connect-manager-${CONNECT_MANAGER_VERSION}.tar.xz" | tar --strip-components=1 -xvJf -

RUN tar \
    --strip-components=1 \
    --exclude=PKG-INFO \
    --exclude=README.md \
    --exclude='*.egg-info' \
    --exclude='setup.*' \
    -xzvf connect-manager-*.tar.gz

RUN rm -f \
    connect-manager-client-*.tar.gz \
    connect_manager_client-*.whl

# Pull and Install Connect .deb
ARG CONNECT_OS=ubuntu22
RUN curl -O https://cdn.posit.co/connect/2025.02/rstudio-connect_2025.02.0~${CONNECT_OS}_amd64.deb \
    && apt-get update \
    && apt-get install -y ./rstudio-connect_2025.02.0~${CONNECT_OS}_amd64.deb \
    && rm -rf rstudio-connect_2025.02.0~${CONNECT_OS}_amd64.deb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy Connect config
COPY test/e2e/config/connect.gcfg /etc/rstudio-connect/rstudio-connect.gcfg

# Copy Bootstrap Key
COPY test/e2e/bootstrap-secret.key /etc/rstudio-connect/bootstrap-secret.key

ENV CONNECT_LICENSE=$(CONNECT_LICENSE)

CMD [ "/opt/connect-manager/connect-manager", \
  "--start-connect", \
  "--connect-binary", "/opt/rstudio-connect/bin/connect", \
  "--connect-user", "rstudio-connect", \
  "--license-manager-binary", "/opt/rstudio-connect/bin/license-manager", \
  "--connect-log", "/var/log/rstudio/rstudio-connect/rstudio-connect.log", \
  "--manager-log", "/var/log/rstudio/rstudio-connect/connect-manager.log", \
  "--connect-config-prefix", "/etc/rstudio-connect", \
  "--connect-config", "rstudio-connect.gcfg", \
  "--manager-port", "4723" ]
