
ui_dir := '../src/connect-client/services/ui/static/'

install:
    yarn install

build:
    yarn build
    cp -r dist/* {{ ui_dir }}

build-dev:
    yarn build-dev
    cp -r dist/* {{ ui_dir }}

serve:
    yarn serve

lint:
    yarn lint
