name: Agent
on:
  workflow_call:
jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "latest"
          use-public-rspm: true
      - name: Install renv package
        run: |
          Rscript -e 'install.packages("renv")'
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: just test
