name: Cypress
on:
  workflow_call:
jobs:
  native:
    env:
      DOCKER: false
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v1
      - uses: actions/download-artifact@v3
        with:
          name: executables
          path: bin
      - run: chmod -R +x ./bin
      - run: just cy install
      - run: just cy test
