name: Image
on:
  workflow_call:
jobs:
  image:
    strategy:
      matrix:
        docker-platform: ["linux/amd64", "linux/arm64"]
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-github-runtime@v3
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v1
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: just image
        env:
          DOCKER_PLATFORM: ${{ matrix.docker-platform }}
