name: JupyterLab
on:
  workflow_call:
jobs:
  native:
    env:
      DOCKER: false
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - run: just jupyterlab ci
