name: Web
on:
  workflow_call:
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: just web install
      - run: just web test
