name: Web
on:
  workflow_call:
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-github-runtime@v3
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v1
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: just web install
      - run: just web lint
      - run: just web test
