alias b := build
alias c := clean
alias i := install
alias l := lint
alias p := preview
alias r := run
alias t := test
alias w := watch

export CYPRESS_CACHE_FOLDER := "./cypress/.cache"

_ci := env_var_or_default("CI", "false")

_debug := env_var_or_default("DEBUG", "false")

_with_debug := if _debug == "true" {
        "set -x pipefail"
    } else {
        ""
    }

default:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    just clean
    just install
    just build


# Compiles the static assests for the web client. Static assets are written to `./web/dist`.
build:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    npm run build

# Deletes ephemeral project files (i.e., cleans the project).
clean:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    rm -rf .quasar
    rm -rf dist
    rm -rf node_modules

# Launch a local web server instance with hot-reloads.
dev:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    npm run dev

# Fixes formatting using ESLint
fix:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    npm run fix

# Installs dependencies
install:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    if [ {{ _ci }} = "true" ]; then
        npm ci --no-audit --no-fund
    else
        npm install --no-audit --no-fund
    fi

# Checks formatting using ESLint
lint:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    npm run lint

format:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    npm run format

check-format:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    npm run check-format

# Launch a local web server instance in production mode.
preview:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    npm run preview

# Executes commands via `npm`. Equivalent to `npm run`. Provides arbitrary command chaining inside of Docker from project root (i.e., `just web run preview`)
run *args:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    npm run {{ args }}


# Executes unit tests
test:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    npm run test

# Watches unit tests
watch:
    #!/usr/bin/env bash
    set -eou pipefail
    {{ _with_debug }}

    npm run watch
