default: install lint test build

install *args:
    yarn install {{ args }}

lint *args: install
    yarn lint {{ args }}

build *args: install
    yarn build {{ args }}

test: install
    yarn test
    go test -race ./...

start:
    yarn start
